name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
            6.0.x 
            7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish wasm
      run: dotnet publish -c Release -o deploy BootstrapBlazor.Client
      
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        GITHUB_TOKEN: ${{ secrets.GH_PUSH_TOKEN }}
        BRANCH: gh-pages
        FOLDER: deploy/wwwroot
        CLEAN: true
    - name: Mirror to Gitee
      uses: Yikun/hub-mirror-action@master
      with:
        # GitHub 源仓库地址
        src: gaofen13/bootstrap-blazor
        # Gitee 目标仓库地址
        dst: gaofen13/bootstrap-blazor
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_MIRROR_TOKEN }}
        account_type: user
